import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/struct/themeprovider";
import Header from "@/components/struct/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import Home from "./page";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "AI Skill",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
        baseTheme: dark,
      }}>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* header */}
            <Header/>
            <main className="min-h-screen">{children}
              
            </main>
            <footer className="bg-muted/40 py-12">
              <div className="container mx-auto px-4 text-center text-cyan-600">
                Copyright @2025 
              </div>
            </footer>
            
          </ThemeProvider>

      </body>
    </html>
    </ClerkProvider>
  );
}
